name: Deploy website to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy react app to github pages
        uses: Vladimir-Urik/react-ghpages@1.0